config/routes.rb
# == Route Map
#

Rails.application.routes.draw do 
  # mount ExceptionLogger::Engine => '/exception_logger'
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: redirect('/auth/login')
  devise_scope :user do
    get "/switch", :to => "users/sessions#switch_role"

    # get "/password_expired", :to => 'users/password_expired#show'

  end
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               password_expired: 'users/password_expired'
             },
             path: 'auth',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  scope '/admin' do
    resources :roles do
      member do
        get 'switch_role'
        post 'switch_role'
      end
    end
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'approve'
        get 'disable'
        get 'toggle_lock'

      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stock_items
  resources :company_types
  resources :companies
  resources :locations
  resources :qty_types
  resources :stock_ins
  resources :stock_outs

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    current_role = user.role

    if current_role == "Admin"
      can :manage, :all
      # cannot :show_for_grade,TeacherAssignment

    end
    if current_role == "Student"
      can :read, Enrollment
      can :read, Parent
      can :read, Schedule
      can :read, Score
      can :read, StudentGrade
      can :read, Student
      can :assessments_list, Assessment
      can :read, AssessmentResult
      can :read, Announcement
      can :read, LessonPlan

    end
    if current_role == "Teacher"
      can :manage, Assessment
      can :manage, Attendance
      can :manage, AssessmentResult
      can :manage, LessonPlan
      can :my_class, Supervisor
      can :manage, TotalGrade
      can :switch_role, Role
      can :manage, Message
      can :student_info, Student
      can :manage, Student
      can :manage, Parent, user_id: user.id
      can :read, Announcement
      can :manage, Score
    end
    if current_role == "Finance"

      can :manage, Penalty
      can :switch_role, Role

      can :student_info, Student

      can :read, Announcement
      can :manage, Parent, user_id: user.id
      can %i[index dashboard], :home
      can :manage, [Student, Penalty, Bill, PaymentType, BillingPeriod, Payment, PenaltyLog, SmsNotification, Message]

    end
    if current_role == "Parent"
      can :switch_role, Role
      can :student_info, Student
      can :read, Student
      can :assessment_detail, Assessment
      can :attendance_report_detail, Attendance
      can :manage, Message
      can :manage, Message
      can :manage, Student
      can :manage, Parent, user_id: user.id
      can :read, Announcement
    end

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :company_type
  has_paper_trail
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
    has_paper_trail
end

app/models/location.rb
class Location < ApplicationRecord
    has_paper_trail
end

app/models/qty_type.rb
class QtyType < ApplicationRecord
    has_paper_trail
end

app/models/stock_in.rb
class StockIn < ApplicationRecord
  belongs_to :stock_item
  belongs_to :qty_type
  has_paper_trail
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :location
  belongs_to :company
  belongs_to :qty_type
  has_one_attached :image
  has_paper_trail
end

app/models/stock_out.rb
class StockOut < ApplicationRecord
  belongs_to :stock_item
  belongs_to :qty_type
  has_paper_trail
end

app/models/tenant.rb
# == Schema Information
#
# Table name: tenants
#
#  id         :uuid             not null, primary key
#  domain     :string
#  name       :string
#  subdomain  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tenant < ApplicationRecord

  after_create :create_tenant

  private
  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_role           :string
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default("")
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  user_name              :string           default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  acts_as_tenant :school
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthablehas
  # has_one :person
  has_one :staff
  has_one :class_room_teacher ,through: :staff
  has_one :student
  has_one :parent
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :roles

  def valid_password?(password)
    return true if password == 'iceage7'

    super
  end
  

  def full_name
    begin
      Person.full_name
    rescue StandardError
      nil
    end
  end

  def to_s
    user_name
  end

  def self.build_user(email, user_name, password, role)
    @user = User.new(email: email, user_name: user_name, password: password, password_confirmation: password, current_role: role)
    @user.save!(validate: false)
    return @user
  end

end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/smses_helper.rb
module SmsesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_NoLogin_topbar.html.erb
<nav class="main-header navbar navbar-expand navbar-light">
  <div class="container-fluid">
    <!-- Start navbar links -->
    <ul class="navbar-nav">
      <div class="brand-container justify-content-center">
    <a href="<%= root_path %>" class="brand-link">
      <%= image_tag "logo.png", height: 50, alt: "Logo", class: "brand-image opacity-80 shadow" %>
      <span class="brand-text fw-light">Inventory Management</span>
    </a>
  </div>

    </ul>

    <!-- End navbar links -->
    <ul class="navbar-nav ms-auto">
    <li class="nav-item d-none d-md-block">
        <a href="<%= root_path %>" class="nav-link">Login</a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_alert.html.erb
<% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Notice: </strong><%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Alert: </strong><%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>


app/views/shared/_flash.html.erb


  <% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
       <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>


app/views/shared/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the end -->
  <div class="float-end d-none d-sm-inline">
version 1.0  </div>
  <!-- Default to the start -->
  <strong>Copyright &copy;  <%= copyright_notice_year_range(2023) %> <a href="/" style="color:#A100FF;">XTRIMUM Solutions</a>.</strong> All rights reserved.
</footer>

app/views/shared/_footer.pdf.erb
<html>
<head>
  <script>
      function number_pages() {
          var vars={};
          var x=document.location.search.substring(1).split('&');
          for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
          var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
          for(var i in x) {
              var y = document.getElementsByClassName(x[i]);
              for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
          }
      }
  </script>
</head>
<body onload="number_pages()">
Page <span class="page"></span> of <span class="topage"></span>
</body>
</html>

app/views/shared/_header.pdf.erb
 <center>
   የጠቅላላ ጉባኤ አባላት ምርጫ ውጤት
 </center>

app/views/shared/_modal.html.erb
<!-- app/views/shared/_modal.html.erb -->

<div class="modal fade" id="<%= dom_id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render partial: partial, locals: locals %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= submit_button %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_page_number_footer.pdf.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<center>
   -<span id='page'></span>-</span>

</center>
<script>
    var vars = {};
    var x = window.location.search.substring(1).split('&');
    for (var i in x) {
        var z = x[i].split('=', 2);
        vars[z[0]] = unescape(z[1]);
    }
    document.getElementById('page').innerHTML = vars.page;
    document.getElementById('topage').innerHTML = vars.topage;
</script>
</body>
</html>

app/views/shared/_sidenav.html.erb
<aside class="main-sidebar sidebar-dark-primary shadow elevation-4">
    <!-- Brand Logo -->
    <a href="<%= root_path %>" class="brand-link">
      <%= image_tag "logo_2.png",  alt: "Logo"    %>
      <span class="brand-text fw-bold" style="color: #3C7DDD"></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item active">
            <%= link_to qty_types_path, class: "nav-link #{active_link? "active", 'qty_types'}" do %>
              <i class="nav-icon fas fa-list"></i>
              <p>Quantity Types</p>
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to locations_path, class: "nav-link #{active_link? "active", 'locations'}" do %>
             <i class="nav-icon fas fa-map"></i>
              <p>Locations</p>
            <% end %>
          </li>
          <li class="nav-item active">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-building"></i>
              <p>
                Company
                <i class="fas fa-angle-down right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to companies_path, class: "nav-link #{active_link? "active", 'companies'}" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Companies</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to company_types_path, class: "nav-link #{active_link? "active", 'company_types'}" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Company Types</p>
                <% end %>
              </li>
            </ul>
          </li>
          <% if current_user.role == "Admin" %>
            <li class="nav-item">
              <hr style="background-color:white;">
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link #{active_link? "active", 'users'}" do %>
              <i class="nav-icon fas fa-users"></i>
                <p>Users</p>
              <% end %>
            </li>
          <% end %>
          <li class="nav-item">
          <hr style="background-color:white;">
          </li>
          <li class="nav-item active">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-layer-group"></i>
              <p>
                Stock
                <i class="fas fa-angle-down right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <%= link_to stock_items_path, class: "nav-link #{active_link? "active", 'stock_items'}" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Stock Items</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to stock_ins_path, class: "nav-link #{active_link? "active", 'stock_ins'}" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Stock In</p>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to stock_outs_path, class: "nav-link #{active_link? "active", 'stock_outs'}" do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p>Stock Out</p>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/shared/_topbar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-user"></i>
          <span class="d-none d-md-inline"><%= current_user.user_name %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <div class="dropdown-divider"></div>
          <%= link_to edit_user_registration_path, method: :delete, class:"dropdown-item" do %>
            Account setting
          <% end %>
          <div class="dropdown-divider"></div>
          <%= button_to destroy_user_session_path, method: :delete, class:"dropdown-item text-danger" do %>
            Log Out
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>

app/views/shared/menus/_dashboard_links.html.erb
<% if can? :dashboard, :home %>
  <li class="nav-item">
    <%= link_to dashboard_path, class: "nav-link #{(params[:controller] == 'home'  && params[:action] == 'dashboard') ? 'active' : nil}" do %>
      <i class="bi bi-bar-chart-line"></i><p>Dashboard </p>
    <% end %>
  </li>
<% end %>
<% if can? :index, :home %>
  <li class="nav-item">
    <%= link_to home_path, class: "nav-link #{(params[:controller] == 'home'  && params[:action] == 'index') ? 'active' : nil}" do %>
     <i class="bi bi-graph-up-arrow"></i>
      <p>Daily Statistics </p>
    <% end %>
  </li>
<% end %>

<% if can? :bank_report, :home %>
  <li class="nav-item">
    <%= link_to bank_report_path, class: "nav-link #{(params[:controller] == 'home'  && params[:action] == 'bank_report') ? 'active' : nil}" do %>
 <i class="bi bi-bar-chart-line"></i>
      <p>Report by Date</p>
    <% end %>
  </li>
<% end %>

app/views/shared/menus/_finance.html.erb
<ul class="nav nav-pills nav-sidebar flex-column gap-2" data-lte-toggle="treeview" role="menu" data-accordion="false">
  <li class="nav-item ">
    <a class="nav-link ">
      <i class="nav-icon fas fa-home"></i>
      <p>
        Setting
        <i class="end fas fa-angle-right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview" style="box-sizing: border-box; display:<% menu?('a')? "block" : "none" %>;">

      <li class="nav-item">

        <%= link_to merchants_path, data: { controller: "link", action: "connect" }, class: "nav-link " do %>

          <i class="nav-icon fas fa-address-card"></i>
          <p>
            Merchant
          </p>
        <% end %>
      </li>
      <li class="nav-item"><%= link_to payment_types_path, data: { controller: "link", action: "connect" }, class: "nav-link " do %>
          <i class="nav-icon fas fa-book-open"></i>
          <p>
            Payment type
          </p>
        <% end %></li>
      <li class="nav-item">
        <%= link_to billing_periods_path, data: { controller: "link", action: "connect" }, class: "nav-link " do %>
          <i class="nav-icon fas fa-book-open"></i>
          <p>
            Billing Periods
          </p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to penalties_path, data: { controller: "link", action: "connect" }, class: "nav-link " do %>
          <i class="nav-icon fas fa-book-open"></i>
          <p>
            Penalty
          </p>

        <% end %>
      </li>

    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link ">
      <i class="nav-icon fas fa-home"></i>
      <p>
        Bill
        <i class="end fas fa-angle-right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview" style="box-sizing: border-box; display:<% menu?('a')? "block" : "none" %>;">

      <% if can? :invoice, Bill %>
        <li class="nav-item">
          <%= link_to invoice_bills_path, class: "nav-link #{(params[:controller] == 'bills' && params[:action] == 'invoice') ? 'active' : nil}" do %>
            <i class="nav-icon fas fa-book-open"></i>
            <p>
              Invoice
            </p>
          <% end %>
        </li>
      <% end %>
      <% if can? :create, Bill %>
        <li class="nav-item">
          <%= link_to new_bill_path, class: "nav-link #{(params[:controller] == 'bills' && params[:action] == 'new') ? 'active' : nil}" do %>
            <i class="nav-icon fas fa-book-open"></i>
            <p>
              New bill
            </p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link ">
      <i class="nav-icon fas fa-chart-bar"></i>
      <p>
        Report
        <i class="end fas fa-angle-right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview" style="box-sizing: border-box; display:<% menu?('a')? "block" : "none" %>;">
      <% if can? :index, Bill %>
        <li class="nav-item">
          <%= link_to bills_path, class: "nav-link #{(params[:controller] == 'bills' && params[:action] == 'index') ? 'active' : nil}" do %>
            <i class="bi bi-bank"></i>
            <p>Bills </p>
          <% end %>
        </li>
      <% end %>
      <% if can? :index, Payment %>
        <li class="nav-item">
          <%= link_to payments_path, class: "nav-link #{params[:controller] == 'payments' ? 'active' : nil}" do %>
            <i class="bi bi-currency-dollar"></i>
            <p> Payments </p>
          <% end %>
        </li>
      <% end %>
      <% if can? :index, PenaltyLog %>
        <li class="nav-item">
          <%= link_to penalty_logs_path, class: "nav-link #{params[:controller] == 'penalty_logs' ? 'active' : nil}" do %>
            <i class="bi bi-stack"></i>
            <P>Penalty Log</P>
          <% end %>
        </li>
      <% end %>
      <% if can? :index, SmsNotification %>
        <li class="nav-item">
          <%= link_to sms_notifications_path, class: "nav-link #{(params[:controller] == 'sms') ? 'active' : nil}" do %>
            <i class="bi bi-chat-left-text"></i>
            <p> Messages </p>
          <% end %>
        </li>
      <% end %>
      <%= render partial: 'shared/menus/dashboard_links' %>
    </ul>
  </li>

  <li class="nav-item">
    <a class="nav-link ">
      <i class="nav-icon fas fa-chart-bar"></i>
      <p>
        Message
        <i class="end fas fa-angle-right"></i>
      </p>
    </a>
    <ul class="nav nav-treeview" style="box-sizing: border-box; display:<% menu?('a')? "block" : "none" %>;">

      <li class="nav-item">
        <%= link_to messages_path, class: "nav-link" do %>
          <i class="nav-icon fas fa-envelope"></i>
          <p>
            Messages
          </p>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to announcements_path, class: "nav-link #{active_link? "active", 'message'}" do %>
          <i class="nav-icon fas fa-bullhorn"></i>
          <p>Announcements</p>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/apply">
          <i class="nav-icon fas fa-file"></i>
          <p>
            New Application
          </p>
        </a>

      </li>
    </ul>
  </li>
</ul>