config/routes.rb
# == Route Map
#

Rails.application.routes.draw do 
  # mount ExceptionLogger::Engine => '/exception_logger'
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: redirect('/auth/login')
  devise_scope :user do
    get "/switch", :to => "users/sessions#switch_role"

    # get "/password_expired", :to => 'users/password_expired#show'

  end
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               password_expired: 'users/password_expired'
             },
             path: 'auth',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  scope '/admin' do
    resources :roles do
      member do
        get 'switch_role'
        post 'switch_role'
      end
    end
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'approve'
        get 'disable'
        get 'toggle_lock'

      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stock_items
  resources :company_types
  resources :companies
  resources :locations
  resources :qty_types
  resources :stock_ins
  resources :stock_outs

end

app/controllers/qty_types_controller.rb
class QtyTypesController < ApplicationController
  before_action :set_qty_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @qty_types = QtyType.all
    respond_with(@qty_types)
  end

  def show
    respond_with(@qty_type)
  end

  def new
    @qty_type = QtyType.new
    respond_with(@qty_type)
  end

  def edit
  end

  def create
    @qty_type = QtyType.new(qty_type_params)
    flash[:notice] = 'QtyType was successfully created.' if @qty_type.save
    redirect_to qty_types_path
  end

  def update
    flash[:notice] = 'QtyType was successfully updated.' if @qty_type.update(qty_type_params)
    respond_with(@qty_type)
  end

  def destroy
    @qty_type.destroy
    respond_with(@qty_type)
  end

  private
    def set_qty_type
      @qty_type = QtyType.find(params[:id])
    end

    def qty_type_params
      params.require(:qty_type).permit(:name)
    end
end

app/helpers/qty_types_helper.rb
module QtyTypesHelper
end

app/views/qty_types/_form.html.erb

<%= simple_form_for(@qty_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-7 ms-lg-5">
    <%= f.input :name %>
  </div>
<div class="card-footer">
  <%= link_to "Back",qty_types_path, class: 'btn btn-xs btn-primary btn-xs'   %>

  <%= f.button :submit, class: "btn btn-xs btn-primary btn-xs" %>
</div>
<% end %>

app/views/qty_types/_qty_type.html.erb
<div id="<%= dom_id qty_type %>">
  <p>
    <strong>Name:</strong>
    <%= qty_type.name %>
  </p>

</div>

app/views/qty_types/edit.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "Edit Qty type" } %>


app/views/qty_types/index.html.erb

<div class="card">
  <div class="card-header">
    <h3 class="card-title"> Qty types</h3>
    <div class="card-tools">
      <% if current_user.role == "Admin" %>
        <%= link_to "New Qty type", new_qty_type_path, class: 'btn btn-sm btn-primary' %>
      <% end %>
    </div>
  </div>
  <!-- /.card-header -->
  <div class="card-body">

  <table class=" dtable table table-striped table-bordered table-hover table-sm table-ligh shadow-sm">
    <thead>
      <tr>
     	  
        <th>Name</th>
        
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @qty_types.each do |qty_type| %>
        <%= content_tag :tr, id: dom_id(qty_type), class: dom_class(qty_type) do %>
           
            <td><%= qty_type.name %></td>
          
          <td>
              <%# <%= link_to "Detail",qty_type, class: 'btn btn-sm btn-primary'   %>

              <% if current_user.role == "Admin" %><%= link_to "Edit" ,edit_qty_type_path(qty_type), class: 'btn btn-sm btn-info'   %><% end %>

              <% if current_user.role == "Admin" %><%= button_to "Delete", qty_type_path(qty_type), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'btn btn-sm btn-danger'  %><% end %>

                </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>


app/views/qty_types/new.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "Edit Qty type" } %>

app/views/qty_types/show.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Qty type
    </h4>
  </div>
  <div class="card-body">
  
    <b>Name:</b>
    <%= @qty_type.name %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to "Edit" ,edit_qty_type_path(@qty_type), class: 'btn btn-sm btn-info'   %>
    <%= button_to "Delete", qty_type_path(@qty_type), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'btn btn-sm btn-danger'  %>


       </div>
</div>