config/routes.rb
# == Route Map
#

Rails.application.routes.draw do 
  # mount ExceptionLogger::Engine => '/exception_logger'
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: redirect('/auth/login')
  devise_scope :user do
    get "/switch", :to => "users/sessions#switch_role"

    # get "/password_expired", :to => 'users/password_expired#show'

  end
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               password_expired: 'users/password_expired'
             },
             path: 'auth',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  scope '/admin' do
    resources :roles do
      member do
        get 'switch_role'
        post 'switch_role'
      end
    end
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'approve'
        get 'disable'
        get 'toggle_lock'

      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stock_items
  resources :company_types
  resources :companies
  resources :locations
  resources :qty_types
  resources :stock_ins
  resources :stock_outs

end

app/models/stock_out.rb
class StockOut < ApplicationRecord
  belongs_to :stock_item
  belongs_to :qty_type
  has_paper_trail
end

app/controllers/stock_outs_controller.rb
class StockOutsController < ApplicationController
  before_action :set_stock_out, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stock_outs = StockOut.all
    respond_with(@stock_outs)
  end

  def show
    respond_with(@stock_out)
  end

  def new
    @stock_out = StockOut.new
    respond_with(@stock_out)
  end

  def edit
  end

  def create
    @stock_out = StockOut.new(stock_out_params)
    stock_item = StockItem.find(@stock_out.stock_item.id)
    if stock_item.qty >= @stock_out.qty
      @stock_out.total = @stock_out.qty * @stock_out.cost
      flash[:notice] = 'StockIn was successfully created.' if @stock_out.save
      stock_item.qty -= @stock_out.qty
      stock_item.save
      redirect_to stock_outs_path
    else
      redirect_to stock_outs_path, alert:"Stock Out request denied!!!"      
    end
    
  end

  def update
    old_qty = @stock_out.qty
    stock_item = StockItem.find(@stock_out.stock_item.id)
    @stock_out.update(stock_out_params)
    
    if ((stock_item.qty + old_qty) - @stock_out.qty) >= 0
      total = @stock_out.qty * @stock_out.cost
      @stock_out.update(total:total)
      
      new_qty = (stock_item.qty + old_qty) - @stock_out.qty
      stock_item.update(qty: new_qty)
      redirect_to stock_outs_path, notice:'StockOut was successfully updated.'
    else
      @stock_out.update(qty:old_qty)
      redirect_to stock_outs_path, alert:"Stock Out Update request denied!!!"
    end

  end

  def destroy
    @stock_out.destroy
    redirect_to stock_outs_path
  end

  private
    def set_stock_out
      @stock_out = StockOut.find(params[:id])
    end

    def stock_out_params
      params.require(:stock_out).permit(:stock_item_id, :qty, :qty_type_id, :cost, :total,:stock_type)
    end
end

app/helpers/stock_outs_helper.rb
module StockOutsHelper
end

app/views/stock_outs/_form.html.erb

<%= simple_form_for(@stock_out) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-7 ms-lg-5">
    <%= f.association :stock_item %>
    <%= f.input :qty, input_html: { min: '0' } %>
    <%= f.association :qty_type %>
    <%= f.input :cost %>
  </div>
<div class="card-footer">
  <%= link_to "Back",stock_outs_path, class: 'btn btn-xs btn-primary btn-xs'   %>

  <%= f.button :submit, class: "btn btn-xs btn-primary btn-xs" %>
</div>
<% end %>

app/views/stock_outs/_stock_out.html.erb
<div id="<%= dom_id stock_out %>">
  <p>
    <strong>Stock item:</strong>
    <%= stock_out.stock_item_id %>
  </p>

  <p>
    <strong>Qty:</strong>
    <%= stock_out.qty %>
  </p>

  <p>
    <strong>Qty type:</strong>
    <%= stock_out.qty_type_id %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= stock_out.cost %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= stock_out.total %>
  </p>

</div>

app/views/stock_outs/edit.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "Edit Stock out" } %>


app/views/stock_outs/index.html.erb

<div class="card">
  <div class="card-header">
    <h3 class="card-title"> Stock outs</h3>
    <div class="card-tools">
      <%= link_to "New Stock out", new_stock_out_path, class: 'btn btn-sm btn-primary' %>



    </div>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="stock_outs_list" class="table table-striped table-bordered table-hover table-sm table-ligh shadow-sm">
      <thead>
        <tr>
          
          <th>Stock item</th>
          
          <th>Qty</th>
          
          <th>Cost</th>
          
          <th>Total</th>

          <th>Created At</th>

          <th>Updated At</th>
          
          <th> </th>
        </tr>
      </thead>
      <tbody>
        <% @stock_outs.each do |stock_out| %>
          <%= content_tag :tr, id: dom_id(stock_out), class: dom_class(stock_out) do %>
            
              <td><%= stock_out.stock_item.name %></td>
            
              <td><%= stock_out.qty %> <%= stock_out.qty_type.name %> </td>
            
              <td><%= stock_out.cost %></td>
            
              <td><%= stock_out.total %></td>

              <td><%= stock_out.created_at.day %> - <%= stock_out.created_at.month %> - <%= stock_out.created_at.year %></td>

              <td><%= stock_out.updated_at.day %> - <%= stock_out.updated_at.month %> - <%= stock_out.updated_at.year %></td>
            
            <td>
                <%= link_to "Detail",stock_out, class: 'btn btn-sm btn-primary'   %>

                <%= link_to "Edit" ,edit_stock_out_path(stock_out), class: 'btn btn-sm btn-info'   %>

                <%# <%= button_to "Delete", stock_out_path(stock_out), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'btn btn-sm btn-danger'  %>

                  </td>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#stock_outs_list').DataTable( {
       dom:
       '<"row justify-content-between mb-2"' +
       '<"col-sm-auto col-12"B>' +
       '<"col-sm-auto col-12"f>' +
       ">" +
       '<"table-responsive"t>' +
       '<"d-flex justify-content-between align-items-center"ip>',
        buttons: [
            {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
            },
            'colvis'
        ]
        } );
    } );
</script>

app/views/stock_outs/new.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "Edit Stock out" } %>

app/views/stock_outs/show.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Stock out
    </h4>
  </div>
  <div class="card-body">
  
    <b>Stock item:</b>
    <%= @stock_out.stock_item %>
    <br>
  
    <b>Qty:</b>
    <%= @stock_out.qty %>
    <br>
  
    <b>Qty type:</b>
    <%= @stock_out.qty_type %>
    <br>
  
    <b>Cost:</b>
    <%= @stock_out.cost %>
    <br>
  
    <b>Total:</b>
    <%= @stock_out.total %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to "Edit" ,edit_stock_out_path(@stock_out), class: 'btn btn-sm btn-info'   %>
    <%= button_to "Delete", stock_out_path(@stock_out), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'btn btn-sm btn-danger'  %>


       </div>
</div>