config/routes.rb
# == Route Map
#

Rails.application.routes.draw do 
  # mount ExceptionLogger::Engine => '/exception_logger'
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  root to: redirect('/auth/login')
  devise_scope :user do
    get "/switch", :to => "users/sessions#switch_role"

    # get "/password_expired", :to => 'users/password_expired#show'

  end
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               password_expired: 'users/password_expired'
             },
             path: 'auth',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }
  scope '/admin' do
    resources :roles do
      member do
        get 'switch_role'
        post 'switch_role'
      end
    end
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'approve'
        get 'disable'
        get 'toggle_lock'

      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stock_items
  resources :company_types
  resources :companies
  resources :locations
  resources :qty_types
  resources :stock_ins
  resources :stock_outs

end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :location
  belongs_to :company
  belongs_to :qty_type
  has_one_attached :image
  has_paper_trail
end

app/controllers/stock_items_controller.rb
class StockItemsController < ApplicationController
  before_action :set_stock_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stock_items = StockItem.all
    respond_with(@stock_items)
  end

  def show
    @stock_ins = StockIn.where(stock_item_id:@stock_item.id)
    @stock_outs = StockOut.where(stock_item_id:@stock_item.id)
    @all = []

    @stock_ins.each do |stock|
      @all << stock
    end
    @stock_outs.each do |stock|
      @all << stock
    end
    @all = @all.sort_by(&:created_at)

    respond_with(@stock_ins, @stock_outs, @all)
  end

  def new
    @stock_item = StockItem.new
    respond_with(@stock_item)
  end

  def edit
  end

  def create
    @stock_item = StockItem.new(stock_item_params)
    @stock_item.qty = 0
    @stock_item.cost = 0
    @stock_item.total = 0
    flash[:notice] = 'StockItem was successfully created.' if @stock_item.save
    redirect_to stock_items_path
  end

  def update
    flash[:notice] = 'StockItem was successfully updated.' if @stock_item.update(stock_item_params)
    redirect_to stock_items_path
  end

  def destroy
    @stock_item.destroy
    redirect_to stock_items_path
  end

  private
    def set_stock_item
      @stock_item = StockItem.find(params[:id])
    end

    def stock_item_params
      params.require(:stock_item).permit(:name, :location_id, :reference, :company_id, :qty, :qty_type_id, :cost, :total, :image)
    end
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/stock_items/_form.html.erb

<%= simple_form_for(@stock_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-7 ms-lg-5">
    <%= f.input :name %>
    <%= f.association :location %>
    <%= f.input :reference %>
    <%= f.association :company %>
    <%= f.input :image %>
  </div>
<div class="card-footer">
  <%= link_to "Back",stock_items_path, class: 'btn btn-xs btn-primary btn-xs'   %>

  <%= f.button :submit, class: "btn btn-xs btn-primary btn-xs" %>
</div>
<% end %>

app/views/stock_items/_stock_item.html.erb
<div id="<%= dom_id stock_item %>">
  <p>
    <strong>Name:</strong>
    <%= stock_item.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= stock_item.location_id %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= stock_item.reference %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= stock_item.company_id %>
  </p>

  <p>
    <strong>Qty:</strong>
    <%= stock_item.qty %>
  </p>

  <p>
    <strong>Qty type:</strong>
    <%= stock_item.qty_type_id %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= stock_item.cost %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= stock_item.total %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to stock_item.image.filename, stock_item.image if stock_item.image.attached? %>
  </p>

</div>

app/views/stock_items/edit.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "Edit Stock item" } %>


app/views/stock_items/index.html.erb

<div class="card">
  <div class="card-header">
    <h3 class="card-title"> Stock items</h3>
    <div class="card-tools">
      <%= link_to "New Stock item", new_stock_item_path, class: 'btn btn-sm btn-primary' %>



    </div>
  </div>
  <!-- /.card-header -->
  <div class="card-body">

  <table id = "stock_items_list" class="table table-striped table-bordered table-hover table-sm table-light shadow-sm">
    <thead>
      <tr>
     	  
        <th>Name</th>
        
        <th>Location</th>
        
        <th>Reference</th>
        
        <th>Company</th>
        
        <th>Qty</th>

        <th>Created At</th>
        
        <th>Image</th>
        
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @stock_items.each do |stock_item| %>
        <%= content_tag :tr, id: dom_id(stock_item), class: dom_class(stock_item) do %>
           
            <td><%= stock_item.name %></td>
          
            <td><%= stock_item.location.name %></td>
          
            <td><%= stock_item.reference %></td>
          
            <td><%= stock_item.company.name %></td>
          
            <td><%= stock_item.qty %> <% if stock_item.qty_type %><%= stock_item.qty_type.name %><% end %></td>

            <td><%= stock_item.created_at.year %> - <%= stock_item.created_at.strftime("%B") %> - <%= stock_item.created_at.day %></td>
          
            <td><%= image_tag(stock_item.image, class:"rounded", style: "width:150px") %></td>
          
          <td>
              <%= link_to "Detail",stock_item, class: 'btn btn-sm btn-primary'   %>

              <%= link_to "Edit" ,edit_stock_item_path(stock_item), class: 'btn btn-sm btn-info'   %>

              <% if current_user.role == "Admin" %><%= button_to "Delete", stock_item_path(stock_item), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'btn btn-sm btn-danger'  %><% end %>

                </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

<script>
  $(document).ready(function() {
    $('#stock_items_list').DataTable( {
       dom:
       '<"row justify-content-between mb-2"' +
       '<"col-sm-auto col-12"B>' +
       '<"col-sm-auto col-12"f>' +
       ">" +
       '<"table-responsive"t>' +
       '<"d-flex justify-content-between align-items-center"ip>',
        buttons: [
            {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
            },
            'colvis'
        ]
        } );
    } );
</script>

app/views/stock_items/new.html.erb
<%= render partial: 'form' , layout: 'layouts/sf_label', locals: { title:  "New Stock item" } %>